-- AlterTable
ALTER TABLE "UserProfile" ADD COLUMN "preferredActivity" TEXT NOT NULL DEFAULT 'LEARNING';
ALTER TABLE "UserProfile" ADD COLUMN "investmentHorizon" TEXT NOT NULL DEFAULT 'Y3_TO_7';
ALTER TABLE "UserProfile" ADD COLUMN "onboardingCompleted" BOOLEAN NOT NULL DEFAULT 0;
ALTER TABLE "UserProfile" ADD COLUMN "isDemo" BOOLEAN NOT NULL DEFAULT 0;
ALTER TABLE "UserProfile" ADD COLUMN "maskDefault" BOOLEAN NOT NULL DEFAULT 0;
